-- Seed Dream Garden items
insert into public.items (
  code,
  name,
  category,
  rarity,
  description,
  image_url,
  is_placeable,
  is_active,
  sort_order,
  created_at,
  updated_at
) values
  ('small_seed', '작은 꽃씨', 'nature', 'common', '꿈의 정원에 처음 심는 작은 씨앗이에요.', null, true, true, 1, now(), now()),
  ('sparkling_leaf', '반짝 풀잎', 'nature', 'common', '햇살을 받으면 반짝이는 풀잎이에요.', null, true, true, 2, now(), now()),
  ('pink_flower', '분홍 꽃', 'nature', 'common', '정원을 화사하게 밝혀 주는 분홍 꽃이에요.', null, true, true, 3, now(), now()),
  ('yellow_flower', '노란 꽃', 'nature', 'common', '기분 좋은 빛을 닮은 노란 꽃이에요.', null, true, true, 4, now(), now()),
  ('tiny_star_piece', '작은 별조각', 'sky', 'common', '밤하늘에서 떨어진 작은 별조각이에요.', null, true, true, 5, now(), now()),
  ('white_cloud', '흰 구름', 'sky', 'common', '정원 위를 둥실 떠다니는 흰 구름이에요.', null, true, true, 6, now(), now()),
  ('small_mushroom', '작은 버섯', 'nature', 'common', '숲속에 살짝 돋아난 귀여운 버섯이에요.', null, true, true, 7, now(), now()),
  ('firefly', '반딧불', 'animal', 'common', '어두운 정원을 작게 밝혀 주는 반딧불이에요.', null, true, true, 8, now(), now()),
  ('yellow_butterfly', '노란 나비', 'animal', 'common', '꽃 사이를 팔랑팔랑 날아다니는 노란 나비예요.', null, true, true, 9, now(), now()),
  ('blue_butterfly', '파란 나비', 'animal', 'common', '맑은 하늘빛을 닮은 파란 나비예요.', null, true, true, 10, now(), now()),
  ('flower_path', '꽃길', 'decor', 'uncommon', '정원을 예쁘게 이어 주는 꽃길이에요.', null, true, true, 11, now(), now()),
  ('small_pond', '작은 연못', 'nature', 'uncommon', '물방울이 반짝이는 작은 연못이에요.', null, true, true, 12, now(), now()),
  ('cloud_lamp', '구름 램프', 'decor', 'uncommon', '포근한 빛을 내는 구름 모양 램프예요.', null, true, true, 13, now(), now()),
  ('jelly_fruit', '젤리 열매', 'nature', 'uncommon', '말랑말랑 달콤해 보이는 꿈의 열매예요.', null, true, true, 14, now(), now()),
  ('dream_mailbox', '꿈의 우체통', 'decor', 'uncommon', '꿈속 편지를 받을 수 있는 우체통이에요.', null, true, true, 15, now(), now()),
  ('moonlight_mushroom', '달빛 버섯', 'nature', 'uncommon', '달빛을 머금고 은은하게 빛나는 버섯이에요.', null, true, true, 16, now(), now()),
  ('starlight_chair', '별빛 의자', 'decor', 'uncommon', '별빛 아래에서 쉬어 갈 수 있는 의자예요.', null, true, true, 17, now(), now()),
  ('rainbow_piece', '무지개 조각', 'sky', 'uncommon', '무지개에서 떨어진 반짝이는 조각이에요.', null, true, true, 18, now(), now()),
  ('cloud_rabbit', '구름 토끼', 'animal', 'rare', '폭신한 구름처럼 가벼운 토끼예요.', null, true, true, 19, now(), now()),
  ('starlight_cat', '별빛 고양이', 'animal', 'rare', '별빛을 따라 조용히 걷는 고양이예요.', null, true, true, 20, now(), now()),
  ('petal_spirit', '꽃잎 정령', 'spirit', 'rare', '꽃잎 사이에 숨어 사는 작은 정령이에요.', null, true, true, 21, now(), now()),
  ('waterdrop_spirit', '물방울 정령', 'spirit', 'rare', '맑은 물방울에서 태어난 정령이에요.', null, true, true, 22, now(), now()),
  ('rainbow_bridge', '무지개 다리', 'decor', 'rare', '정원과 하늘을 이어 주는 무지개 다리예요.', null, true, true, 23, now(), now()),
  ('tiny_fairy_house', '작은 요정집', 'decor', 'rare', '요정이 살 것 같은 작은 집이에요.', null, true, true, 24, now(), now()),
  ('fox_spirit', '여우 정령', 'spirit', 'epic', '숲을 지켜 주는 신비한 여우 정령이에요.', null, true, true, 25, now(), now()),
  ('moonlight_deer', '달빛 사슴', 'animal', 'epic', '달빛을 따라 나타나는 고요한 사슴이에요.', null, true, true, 26, now(), now()),
  ('aurora_tree', '오로라 나무', 'nature', 'epic', '하늘빛 오로라를 품은 특별한 나무예요.', null, true, true, 27, now(), now()),
  ('tiny_sky_island', '작은 하늘섬', 'sky', 'epic', '하늘 위에 떠 있는 작은 꿈의 섬이에요.', null, true, true, 28, now(), now()),
  ('galaxy_whale', '은하 고래', 'legend', 'legendary', '밤하늘 은하수를 헤엄치는 전설의 고래예요.', null, true, true, 29, now(), now()),
  ('rainbow_unicorn', '무지개 유니콘', 'legend', 'legendary', '무지개 끝에서 찾아온 전설의 유니콘이에요.', null, true, true, 30, now(), now())
on conflict (code) do update set
  name = excluded.name,
  category = excluded.category,
  rarity = excluded.rarity,
  description = excluded.description,
  image_url = excluded.image_url,
  is_placeable = excluded.is_placeable,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = now();
